#--*--coding:utf-8
#Author:cnn
name_list=["张三","李四","王五"]
list_02=[]
list_02.append("one")
list_02.append(True)
list_02.append(1)
list_02.append(2.1)
list_01=[1,"gust",True,{"1":"cui"},name_list,list_02]
print(name_list)
print(list_02)
print(list_01)
